---
- name: Deploy the app on the server
  hosts: all
  remote_user: azureuser
  tasks:
    - name: Copy the sources
      synchronize:
        src: ../app/
        dest: /home/azureuser/app/
        delete: yes

    - name: Stop app services
      shell:
        docker-compose down
      args:
        chdir:
          /home/azureuser/app

    - name: Build app services
      shell:
        docker-compose build
      args:
        chdir:
          /home/azureuser/app

    - name: Start app services
      shell:
        docker-compose up --detach
      args:
        chdir:
          /home/azureuser/app
